### ISSUE TITLE
real life examples

### ISSUE THREAD

**Issue by job** [bgp/draft-grow-bgp-session-culling#11]
how many examples should we include, and which ones should we include?

current set of examples is nicely diverse, but SR-OS for instance is not commonly used at IXPs. 

I don't think it'll be good to include each and every platform on the planet, I suggest we select 3 - but which 3?

**Comment by moghaddas** [comment]
JunOS, IOS[-XE], Bird or ExaBGP

**Comment by job** [comment]
Those are BGP speakers, not layer-2 switching implementations.

**Comment by moghaddas** [comment]
Oh Sorry, thought you're looking for speakers. I'll remove my comments to prevent confusion :)

**Comment by grizz** [comment]
Definitely not more than 3 IMO -- although, there's nothing stopping us from making an examples directory in this repo to add others if people contribute them.

Agree that SR-OS isn't widely used, but what is? Brocade?

**Comment by job** [comment]
We'll just leave the three examples in the draft, and any additional ones can be added to the specific github repository set up for this purpose: https://github.com/bgp/draft-grow-bgp-session-culling/commit/635bb77b0360dafb2a093378060d5d5690fb9e4a

**Comment by job** [comment]
Repo is here https://github.com/bgp/bgp-session-culling-config-examples
