### ISSUE TITLE
tore's comment

### ISSUE THREAD

**Issue by job** [bgp/draft-grow-bgp-session-culling#9]
https://www.ietf.org/mail-archive/web/grow/current/msg03924.html

**Comment by job** [comment]
A follow-up with suggested text https://www.ietf.org/mail-archive/web/grow/current/msg03944.html

**Comment by job** [comment]
@nickhilliard

**Comment by toreanderson** [comment]
[As requested](https://www.ietf.org/mail-archive/web/grow/current/msg03927.html) by @job, there's now a pull request in #14.

**Comment by job** [comment]
fixed through https://github.com/bgp/draft-grow-bgp-session-culling/pull/14
